package View;

import Control.PeopleController;

import Model.Cachorro;
import Model.Gato;
import Model.Cliente;
import Model.Veterinario;
import Model.Endereço;
import Model.Animal;

import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author antonio
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelClient = new javax.swing.JPanel();
        jPanelClientForm = new javax.swing.JPanel();
        jLabelClientRegister = new javax.swing.JLabel();
        jLabelClientID = new javax.swing.JLabel();
        jTextFieldClientID = new javax.swing.JTextField();
        jLabelClientName = new javax.swing.JLabel();
        jTextFieldClientName = new javax.swing.JTextField();
        jLabelClientCPF = new javax.swing.JLabel();
        jTextFieldClientCPF = new javax.swing.JTextField();
        jLabelClientStreet = new javax.swing.JLabel();
        jTextFieldClientStreet = new javax.swing.JTextField();
        jLabelClientCity = new javax.swing.JLabel();
        jTextFieldClientCity = new javax.swing.JTextField();
        jLabelClientNeighborhood = new javax.swing.JLabel();
        jTextFieldClientNeighborhood = new javax.swing.JTextField();
        jLabelClientNumber = new javax.swing.JLabel();
        jTextFieldClientNumber = new javax.swing.JTextField();
        jLabelClientPhoneNumber = new javax.swing.JLabel();
        jTextFieldClientPhoneNumber = new javax.swing.JTextField();
        jButtonRegisterClient = new javax.swing.JButton();
        jButtonCancelClient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelPet = new javax.swing.JPanel();
        jPanelPetForm = new javax.swing.JPanel();
        jLabelPetRegister = new javax.swing.JLabel();
        jPanelPetOwner = new javax.swing.JPanel();
        jLabelSearchByPetOwnerID = new javax.swing.JLabel();
        jTextFieldPetOwnerID = new javax.swing.JTextField();
        jButtonSearchOwner = new javax.swing.JButton();
        jLabelPetOwnerName = new javax.swing.JLabel();
        jTextFieldPetOwnerName = new javax.swing.JTextField();
        jLabelPetID = new javax.swing.JLabel();
        jTextFieldPetID = new javax.swing.JTextField();
        jLabelPetAge = new javax.swing.JLabel();
        jTextFieldPetAge = new javax.swing.JTextField();
        jLabelPetName = new javax.swing.JLabel();
        jTextFieldPetName = new javax.swing.JTextField();
        jLabelPetType = new javax.swing.JLabel();
        jComboBoxPetType = new javax.swing.JComboBox<>();
        jLabelPetBreed = new javax.swing.JLabel();
        jTextFieldPetBreed = new javax.swing.JTextField();
        jButtonRegisterPet = new javax.swing.JButton();
        jButtonCancelPet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelVeterinary = new javax.swing.JPanel();
        jPanelVeterinaryForm = new javax.swing.JPanel();
        jLabelVetRegister = new javax.swing.JLabel();
        jLabelVetSex = new javax.swing.JLabel();
        jComboBoxVetSex = new javax.swing.JComboBox<>();
        jLabelVetName = new javax.swing.JLabel();
        jTextFieldVetName = new javax.swing.JTextField();
        jLabelVetCPF = new javax.swing.JLabel();
        jTextFieldVetCPF = new javax.swing.JTextField();
        jLabelVetStreet = new javax.swing.JLabel();
        jTextFieldVetStreet = new javax.swing.JTextField();
        jLabelVetCity = new javax.swing.JLabel();
        jTextFieldVetCity = new javax.swing.JTextField();
        jLabelVetNeighborhood = new javax.swing.JLabel();
        jTextFieldVetNeighborhood = new javax.swing.JTextField();
        jLabelVetNumber = new javax.swing.JLabel();
        jTextFieldVetNumber = new javax.swing.JTextField();
        jLabelVetPhoneNumber = new javax.swing.JLabel();
        jTextFieldVetPhoneNumber = new javax.swing.JTextField();
        jLabelCRV = new javax.swing.JLabel();
        jTextFieldVetCRV = new javax.swing.JTextField();
        jLabelVetSpecialty = new javax.swing.JLabel();
        jTextFieldVetSpecialty = new javax.swing.JTextField();
        jButtonRegisterVet = new javax.swing.JButton();
        jButtonCancelVet = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelShowData = new javax.swing.JPanel();
        jPanelDataInfo = new javax.swing.JPanel();
        jButtonShowClients = new javax.swing.JButton();
        jButtonShowVeterinaries = new javax.swing.JButton();
        jScrollPaneData = new javax.swing.JScrollPane();
        jTextAreaData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelClientForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelClientRegister.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabelClientRegister.setText("Cadastrar Cliente");

        jLabelClientID.setText("ID:");

        jLabelClientName.setText("Nome:");

        jLabelClientCPF.setText("CPF:");

        jLabelClientStreet.setText("Rua:");

        jLabelClientCity.setText("Cidade:");

        jLabelClientNeighborhood.setText("Bairro:");

        jLabelClientNumber.setText("Número:");

        jLabelClientPhoneNumber.setText("Celular:");

        jTextFieldClientPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClientPhoneNumberActionPerformed(evt);
            }
        });

        jButtonRegisterClient.setText("Cadastrar");
        jButtonRegisterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterClientActionPerformed(evt);
            }
        });

        jButtonCancelClient.setText("Cancelar");
        jButtonCancelClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelClientActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/iconfinder_38_Target_Audience_1688838 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanelClientFormLayout = new javax.swing.GroupLayout(jPanelClientForm);
        jPanelClientForm.setLayout(jPanelClientFormLayout);
        jPanelClientFormLayout.setHorizontalGroup(
            jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonRegisterClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelClient)
                .addGap(140, 140, 140))
            .addGroup(jPanelClientFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientFormLayout.createSequentialGroup()
                        .addComponent(jLabelClientRegister)
                        .addContainerGap(476, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientFormLayout.createSequentialGroup()
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClientPhoneNumber)
                            .addComponent(jLabelClientNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientNeighborhood, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientCity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientStreet, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldClientNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jTextFieldClientNeighborhood, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientCity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientStreet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientID)
                            .addComponent(jTextFieldClientPhoneNumber))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelClientFormLayout.setVerticalGroup(
            jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClientRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientFormLayout.createSequentialGroup()
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientID)
                            .addComponent(jTextFieldClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientName)
                            .addComponent(jTextFieldClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientCPF)
                            .addComponent(jTextFieldClientCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientStreet)
                            .addComponent(jTextFieldClientStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldClientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelClientCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientNeighborhood)
                            .addComponent(jTextFieldClientNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientNumber)
                            .addComponent(jTextFieldClientNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClientPhoneNumber)
                            .addComponent(jTextFieldClientPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelClient)
                    .addComponent(jButtonRegisterClient))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelClientLayout = new javax.swing.GroupLayout(jPanelClient);
        jPanelClient.setLayout(jPanelClientLayout);
        jPanelClientLayout.setHorizontalGroup(
            jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelClientLayout.setVerticalGroup(
            jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientLayout.createSequentialGroup()
                .addComponent(jPanelClientForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Cliente", jPanelClient);

        jPanelPetForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPetRegister.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabelPetRegister.setText("Cadastrar Animal");

        jPanelPetOwner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSearchByPetOwnerID.setText("Buscar pelo ID do cliente:");

        jButtonSearchOwner.setText("Buscar");
        jButtonSearchOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchOwnerActionPerformed(evt);
            }
        });

        jLabelPetOwnerName.setText("Nome encontrado:");

        javax.swing.GroupLayout jPanelPetOwnerLayout = new javax.swing.GroupLayout(jPanelPetOwner);
        jPanelPetOwner.setLayout(jPanelPetOwnerLayout);
        jPanelPetOwnerLayout.setHorizontalGroup(
            jPanelPetOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPetOwnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPetOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSearchByPetOwnerID)
                    .addComponent(jLabelPetOwnerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPetOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPetOwnerID)
                    .addComponent(jTextFieldPetOwnerName))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPetOwnerLayout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jButtonSearchOwner)
                .addGap(187, 187, 187))
        );
        jPanelPetOwnerLayout.setVerticalGroup(
            jPanelPetOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPetOwnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPetOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchByPetOwnerID)
                    .addComponent(jTextFieldPetOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearchOwner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPetOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPetOwnerName)
                    .addComponent(jTextFieldPetOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelPetID.setText("ID:");

        jLabelPetAge.setText("Idade:");

        jLabelPetName.setText("Nome:");

        jTextFieldPetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPetNameActionPerformed(evt);
            }
        });

        jLabelPetType.setText("Tipo:");

        jComboBoxPetType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachorro", "Gato" }));

        jLabelPetBreed.setText("Raça:");

        jButtonRegisterPet.setText("Cadastrar");
        jButtonRegisterPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterPetActionPerformed(evt);
            }
        });

        jButtonCancelPet.setText("Cancelar");
        jButtonCancelPet.setToolTipText("");
        jButtonCancelPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelPetActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/iconfinder_cat-approve-animal-pet-wild-domestic_3204665.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPetFormLayout = new javax.swing.GroupLayout(jPanelPetForm);
        jPanelPetForm.setLayout(jPanelPetFormLayout);
        jPanelPetFormLayout.setHorizontalGroup(
            jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPetFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPetRegister)
                .addGap(59, 477, Short.MAX_VALUE))
            .addGroup(jPanelPetFormLayout.createSequentialGroup()
                .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPetFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPetFormLayout.createSequentialGroup()
                                .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPetID)
                                    .addComponent(jLabelPetAge)
                                    .addComponent(jLabelPetName)
                                    .addComponent(jLabelPetType)
                                    .addComponent(jLabelPetBreed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxPetType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPetAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPetName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPetID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPetBreed)))
                            .addComponent(jPanelPetOwner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPetFormLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButtonRegisterPet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelPet)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPetFormLayout.setVerticalGroup(
            jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPetFormLayout.createSequentialGroup()
                .addComponent(jLabelPetRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPetFormLayout.createSequentialGroup()
                        .addComponent(jPanelPetOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPetID)
                            .addComponent(jTextFieldPetID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPetAge)
                            .addComponent(jTextFieldPetAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPetName)
                            .addComponent(jTextFieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPetType)
                            .addComponent(jComboBoxPetType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPetBreed)
                            .addComponent(jTextFieldPetBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPetFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRegisterPet)
                            .addComponent(jButtonCancelPet)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPetLayout = new javax.swing.GroupLayout(jPanelPet);
        jPanelPet.setLayout(jPanelPetLayout);
        jPanelPetLayout.setHorizontalGroup(
            jPanelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPetForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPetLayout.setVerticalGroup(
            jPanelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPetLayout.createSequentialGroup()
                .addComponent(jPanelPetForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Animal", jPanelPet);

        jPanelVeterinaryForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelVetRegister.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabelVetRegister.setText("Cadastrar Veterinário");

        jLabelVetSex.setText("Sexo:");

        jComboBoxVetSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        jLabelVetName.setText("Nome:");

        jLabelVetCPF.setText("CPF:");

        jLabelVetStreet.setText("Rua:");

        jLabelVetCity.setText("Cidade:");

        jLabelVetNeighborhood.setText("Bairro:");

        jLabelVetNumber.setText("Número:");

        jLabelVetPhoneNumber.setText("Celular:");

        jTextFieldVetPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVetPhoneNumberActionPerformed(evt);
            }
        });

        jLabelCRV.setText("CRV:");

        jLabelVetSpecialty.setText("Especialidade:");

        jButtonRegisterVet.setText("Cadastrar");
        jButtonRegisterVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterVetActionPerformed(evt);
            }
        });

        jButtonCancelVet.setText("Cancelar");
        jButtonCancelVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelVetActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/iconfinder_virus-14_5862582.png"))); // NOI18N

        javax.swing.GroupLayout jPanelVeterinaryFormLayout = new javax.swing.GroupLayout(jPanelVeterinaryForm);
        jPanelVeterinaryForm.setLayout(jPanelVeterinaryFormLayout);
        jPanelVeterinaryFormLayout.setHorizontalGroup(
            jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeterinaryFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVeterinaryFormLayout.createSequentialGroup()
                            .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelVetCity)
                                .addComponent(jLabelVetStreet))
                            .addGap(24, 24, 24)
                            .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldVetStreet)
                                .addComponent(jTextFieldVetCity)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVeterinaryFormLayout.createSequentialGroup()
                            .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelVetNeighborhood)
                                .addComponent(jLabelVetNumber)
                                .addComponent(jLabelVetPhoneNumber))
                            .addGap(15, 15, 15)
                            .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldVetPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldVetNeighborhood, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(jTextFieldVetNumber)))))
                    .addComponent(jLabelVetRegister)
                    .addGroup(jPanelVeterinaryFormLayout.createSequentialGroup()
                        .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVetName)
                            .addComponent(jLabelVetCPF)
                            .addComponent(jLabelVetSex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxVetSex, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelVeterinaryFormLayout.createSequentialGroup()
                                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldVetName, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(jTextFieldVetCPF))
                                .addGap(203, 203, 203)
                                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelVeterinaryFormLayout.createSequentialGroup()
                                        .addComponent(jLabelCRV)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldVetCRV))
                                    .addGroup(jPanelVeterinaryFormLayout.createSequentialGroup()
                                        .addComponent(jLabelVetSpecialty)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVetSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVeterinaryFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegisterVet)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelVet)
                .addGap(137, 137, 137))
        );
        jPanelVeterinaryFormLayout.setVerticalGroup(
            jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeterinaryFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVetRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVetName)
                    .addComponent(jTextFieldVetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCRV)
                    .addComponent(jTextFieldVetCRV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVetCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVetCPF)
                    .addComponent(jLabelVetSpecialty)
                    .addComponent(jTextFieldVetSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVetSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVetSex))
                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVeterinaryFormLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVetStreet)
                            .addComponent(jTextFieldVetStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVetCity)
                            .addComponent(jTextFieldVetCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVetNeighborhood)
                            .addComponent(jTextFieldVetNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVetNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVetPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVetPhoneNumber)))
                    .addGroup(jPanelVeterinaryFormLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVeterinaryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelVet)
                    .addComponent(jButtonRegisterVet))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanelVeterinaryLayout = new javax.swing.GroupLayout(jPanelVeterinary);
        jPanelVeterinary.setLayout(jPanelVeterinaryLayout);
        jPanelVeterinaryLayout.setHorizontalGroup(
            jPanelVeterinaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVeterinaryForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelVeterinaryLayout.setVerticalGroup(
            jPanelVeterinaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeterinaryLayout.createSequentialGroup()
                .addComponent(jPanelVeterinaryForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Veterinário", jPanelVeterinary);

        jPanelDataInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonShowClients.setText("Mostrar Clientes");
        jButtonShowClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowClientsActionPerformed(evt);
            }
        });

        jButtonShowVeterinaries.setText("Exibir Veterinários");
        jButtonShowVeterinaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowVeterinariesActionPerformed(evt);
            }
        });

        jTextAreaData.setColumns(20);
        jTextAreaData.setRows(5);
        jScrollPaneData.setViewportView(jTextAreaData);

        javax.swing.GroupLayout jPanelDataInfoLayout = new javax.swing.GroupLayout(jPanelDataInfo);
        jPanelDataInfo.setLayout(jPanelDataInfoLayout);
        jPanelDataInfoLayout.setHorizontalGroup(
            jPanelDataInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataInfoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelDataInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDataInfoLayout.createSequentialGroup()
                        .addComponent(jButtonShowClients)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonShowVeterinaries))
                    .addComponent(jScrollPaneData, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelDataInfoLayout.setVerticalGroup(
            jPanelDataInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataInfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelDataInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShowClients)
                    .addComponent(jButtonShowVeterinaries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneData, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelShowDataLayout = new javax.swing.GroupLayout(jPanelShowData);
        jPanelShowData.setLayout(jPanelShowDataLayout);
        jPanelShowDataLayout.setHorizontalGroup(
            jPanelShowDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDataInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelShowDataLayout.setVerticalGroup(
            jPanelShowDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDataInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Exibir Dados", jPanelShowData);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldClientPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClientPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClientPhoneNumberActionPerformed

    private void jButtonRegisterPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterPetActionPerformed
        int ownerID;
        int ID;
        int age;
        try{
           ownerID = Integer.parseInt(jTextFieldPetOwnerID.getText());
           age = Integer.parseInt(jTextFieldPetAge.getText());
           ID = Integer.parseInt(jTextFieldPetID.getText());
        } catch(Exception e){
           ownerID = 0;
           age = 0;
           ID = 0;
        }
        
        String name = jTextFieldPetName.getText();
        String type = jComboBoxPetType.getSelectedItem().toString();
        String breed = jTextFieldPetBreed.getText();
        
        PeopleController controller = new PeopleController();
        
        controller.createPet(ID, ownerID, age, name, type, breed);
        JOptionPane.showMessageDialog(null, "Animal cadastrado com sucesso!"); 
        
    }//GEN-LAST:event_jButtonRegisterPetActionPerformed

    private void jTextFieldPetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPetNameActionPerformed

    private void jTextFieldVetPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVetPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVetPhoneNumberActionPerformed

    private void jButtonCancelVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelVetActionPerformed
        jTextFieldVetName.setText("");
        jTextFieldVetCPF.setText("");
        jTextFieldVetStreet.setText("");
        jTextFieldVetCity.setText("");
        jTextFieldVetNeighborhood.setText("");
        jTextFieldVetNumber.setText("");
        jTextFieldVetPhoneNumber.setText("");
        jTextFieldVetCRV.setText("");
        jTextFieldVetSpecialty.setText("");
    }//GEN-LAST:event_jButtonCancelVetActionPerformed

    private void jButtonRegisterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterClientActionPerformed
        int ID; 
        try{
            ID = Integer.parseInt(jTextFieldClientID.getText());
        } catch(Exception e){
            ID = 0;
        }
        
        String name = jTextFieldClientName.getText();
        String CPF = jTextFieldClientCPF.getText();
        String phoneNumber = jTextFieldClientPhoneNumber.getText();
          
        String street = jTextFieldClientStreet.getText();
        String city = jTextFieldClientCity.getText();
        String neighborhood = jTextFieldClientNeighborhood.getText();
        int number = Integer.parseInt(jTextFieldClientNumber.getText());
        
        PeopleController controller = new PeopleController();
        ArrayList<Animal> a = new ArrayList<>();
        Endereço endereco = new Endereço(street, city, neighborhood, number);
        
        controller.createClients(new Cliente(ID, a, name, CPF, endereco, phoneNumber));
        JOptionPane.showMessageDialog(null,"Cliente cadastrado!");

    }//GEN-LAST:event_jButtonRegisterClientActionPerformed

    private void jButtonSearchOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchOwnerActionPerformed
        int ID;
        try{        
            ID = Integer.parseInt(jTextFieldPetOwnerID.getText());
        } catch (Exception e){
            ID = 0;
        }
        
        PeopleController clientController = new PeopleController();
        
        int index = clientController.retornoIndexClient(ID);
        String ownerName = (clientController.getClientes()).get(index).getNome();

        jTextFieldPetOwnerName.setText(ownerName);
        
        
        
    }//GEN-LAST:event_jButtonSearchOwnerActionPerformed

    private void jButtonRegisterVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterVetActionPerformed
        
        String name = jTextFieldVetName.getText();
        String sex = jComboBoxVetSex.getSelectedItem().toString();
        String CPF = jTextFieldVetCPF.getText();
        String phoneNumber = jTextFieldVetPhoneNumber.getText();
        String CRV = jTextFieldVetCRV.getText();
        String speciality = jTextFieldVetSpecialty.getText();
        
        String street = jTextFieldVetStreet.getText();
        String city = jTextFieldVetCity.getText();
        String neighborhood = jTextFieldVetNeighborhood.getText();
        int number = Integer.parseInt(jTextFieldClientNumber.getText());
        
        PeopleController controller = new PeopleController();
        Endereço endereco = new Endereço(street, city, neighborhood, number);
        
        controller.createVeterinary(new Veterinario(CRV, speciality, name, CPF, endereco, phoneNumber));
        JOptionPane.showMessageDialog(null,"Veterinário cadastrado!");

    }//GEN-LAST:event_jButtonRegisterVetActionPerformed

    private void jButtonShowClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowClientsActionPerformed
        jTextAreaData.setText("");
        
        PeopleController controller = new PeopleController();
        ArrayList<Cliente> clients = controller.getClientes();
        
        if (clients.isEmpty())
            jTextAreaData.append("Nenhum cliente a ser exibido");
        else{
            for(int i = 0; i < clients.size(); i++){
                Cliente client = (Cliente) clients.get(i);
                jTextAreaData.append("======================================\n");
                jTextAreaData.append("                Cliente " + (i+1) + "\n");
                jTextAreaData.append("======================================\n");
                
                jTextAreaData.append(client.toString());

                for(int j = 0; j < client.getAnimais().size(); j++){
                    Animal pet = client.getAnimais().get(j);
                    String type = null;
                    if (pet.getClass() == Cachorro.class)
                        type = "Cachorro";
                    else if (pet.getClass() == Gato.class)
                        type = "Gato";
                    
                    jTextAreaData.append("\nAnimal " + (j+1) + ": "+type+ "\n");
                    jTextAreaData.append(pet.toString());
                }
                
                jTextAreaData.append("======================================\n");
            }
        }
        
        
    }//GEN-LAST:event_jButtonShowClientsActionPerformed

    private void jButtonShowVeterinariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowVeterinariesActionPerformed
         jTextAreaData.setText("");
         
        PeopleController controller = new PeopleController();
        ArrayList<Veterinario> veterinaries = controller.getVeterinarios();
        
        if (veterinaries.isEmpty())
            jTextAreaData.append("Nenhum veterinário a ser exibido");
        else{
            for(int i = 0; i < veterinaries.size(); i++){
                Veterinario veterinary = (Veterinario) veterinaries.get(i);
                jTextAreaData.append("======================================\n");
                jTextAreaData.append("        Veterinário " + (i+1) + "\n"  );
                jTextAreaData.append("======================================\n");
                
                jTextAreaData.append(veterinary.toString());
                
                jTextAreaData.append("======================================\n");
            }
        }
    }//GEN-LAST:event_jButtonShowVeterinariesActionPerformed
    

    private void jButtonCancelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelClientActionPerformed
        jTextFieldClientID.setText("");
        jTextFieldClientName.setText("");
        jTextFieldClientCPF.setText("");
        jTextFieldClientStreet.setText("");
        jTextFieldClientCity.setText("");
        jTextFieldClientNeighborhood.setText("");
        jTextFieldClientNumber.setText("");
        jTextFieldClientPhoneNumber.setText("");
    }//GEN-LAST:event_jButtonCancelClientActionPerformed

    private void jButtonCancelPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelPetActionPerformed
        jTextFieldPetOwnerID.setText("");
        jTextFieldPetOwnerName.setText("");
        jTextFieldPetID.setText("");
        jTextFieldPetAge.setText("");
        jTextFieldPetName.setText("");
        jTextFieldPetBreed.setText("");
    }//GEN-LAST:event_jButtonCancelPetActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelClient;
    private javax.swing.JButton jButtonCancelPet;
    private javax.swing.JButton jButtonCancelVet;
    private javax.swing.JButton jButtonRegisterClient;
    private javax.swing.JButton jButtonRegisterPet;
    private javax.swing.JButton jButtonRegisterVet;
    private javax.swing.JButton jButtonSearchOwner;
    private javax.swing.JButton jButtonShowClients;
    private javax.swing.JButton jButtonShowVeterinaries;
    private javax.swing.JComboBox<String> jComboBoxPetType;
    private javax.swing.JComboBox<String> jComboBoxVetSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCRV;
    private javax.swing.JLabel jLabelClientCPF;
    private javax.swing.JLabel jLabelClientCity;
    private javax.swing.JLabel jLabelClientID;
    private javax.swing.JLabel jLabelClientName;
    private javax.swing.JLabel jLabelClientNeighborhood;
    private javax.swing.JLabel jLabelClientNumber;
    private javax.swing.JLabel jLabelClientPhoneNumber;
    private javax.swing.JLabel jLabelClientRegister;
    private javax.swing.JLabel jLabelClientStreet;
    private javax.swing.JLabel jLabelPetAge;
    private javax.swing.JLabel jLabelPetBreed;
    private javax.swing.JLabel jLabelPetID;
    private javax.swing.JLabel jLabelPetName;
    private javax.swing.JLabel jLabelPetOwnerName;
    private javax.swing.JLabel jLabelPetRegister;
    private javax.swing.JLabel jLabelPetType;
    private javax.swing.JLabel jLabelSearchByPetOwnerID;
    private javax.swing.JLabel jLabelVetCPF;
    private javax.swing.JLabel jLabelVetCity;
    private javax.swing.JLabel jLabelVetName;
    private javax.swing.JLabel jLabelVetNeighborhood;
    private javax.swing.JLabel jLabelVetNumber;
    private javax.swing.JLabel jLabelVetPhoneNumber;
    private javax.swing.JLabel jLabelVetRegister;
    private javax.swing.JLabel jLabelVetSex;
    private javax.swing.JLabel jLabelVetSpecialty;
    private javax.swing.JLabel jLabelVetStreet;
    private javax.swing.JPanel jPanelClient;
    private javax.swing.JPanel jPanelClientForm;
    private javax.swing.JPanel jPanelDataInfo;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelPet;
    private javax.swing.JPanel jPanelPetForm;
    private javax.swing.JPanel jPanelPetOwner;
    private javax.swing.JPanel jPanelShowData;
    private javax.swing.JPanel jPanelVeterinary;
    private javax.swing.JPanel jPanelVeterinaryForm;
    private javax.swing.JScrollPane jScrollPaneData;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaData;
    private javax.swing.JTextField jTextFieldClientCPF;
    private javax.swing.JTextField jTextFieldClientCity;
    private javax.swing.JTextField jTextFieldClientID;
    private javax.swing.JTextField jTextFieldClientName;
    private javax.swing.JTextField jTextFieldClientNeighborhood;
    private javax.swing.JTextField jTextFieldClientNumber;
    private javax.swing.JTextField jTextFieldClientPhoneNumber;
    private javax.swing.JTextField jTextFieldClientStreet;
    private javax.swing.JTextField jTextFieldPetAge;
    private javax.swing.JTextField jTextFieldPetBreed;
    private javax.swing.JTextField jTextFieldPetID;
    private javax.swing.JTextField jTextFieldPetName;
    private javax.swing.JTextField jTextFieldPetOwnerID;
    private javax.swing.JTextField jTextFieldPetOwnerName;
    private javax.swing.JTextField jTextFieldVetCPF;
    private javax.swing.JTextField jTextFieldVetCRV;
    private javax.swing.JTextField jTextFieldVetCity;
    private javax.swing.JTextField jTextFieldVetName;
    private javax.swing.JTextField jTextFieldVetNeighborhood;
    private javax.swing.JTextField jTextFieldVetNumber;
    private javax.swing.JTextField jTextFieldVetPhoneNumber;
    private javax.swing.JTextField jTextFieldVetSpecialty;
    private javax.swing.JTextField jTextFieldVetStreet;
    // End of variables declaration//GEN-END:variables
}
