/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import Model.Pangrama;
import javax.swing.JOptionPane;

/**
 *
 * @author antonio
 */
public class MainWindow extends javax.swing.JFrame {
    Pangrama p = new Pangrama();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        p.createPangramas();
        initComponents();
        lblText.setText(p.takePangran());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btOne = new javax.swing.JButton();
        btTil = new javax.swing.JButton();
        btTwo = new javax.swing.JButton();
        btThree = new javax.swing.JButton();
        btFour = new javax.swing.JButton();
        btFive = new javax.swing.JButton();
        btSix = new javax.swing.JButton();
        btSeven = new javax.swing.JButton();
        btEight = new javax.swing.JButton();
        btNine = new javax.swing.JButton();
        btZero = new javax.swing.JButton();
        btMinus = new javax.swing.JButton();
        btBackspace = new javax.swing.JButton();
        btTab = new javax.swing.JButton();
        btCaps = new javax.swing.JButton();
        btShift = new javax.swing.JButton();
        btP = new javax.swing.JButton();
        btColcheteEsquerdo = new javax.swing.JButton();
        btW = new javax.swing.JButton();
        btColcheteDireito = new javax.swing.JButton();
        btQ = new javax.swing.JButton();
        btE = new javax.swing.JButton();
        btR = new javax.swing.JButton();
        btT = new javax.swing.JButton();
        btY = new javax.swing.JButton();
        btU = new javax.swing.JButton();
        btI = new javax.swing.JButton();
        btO = new javax.swing.JButton();
        btBarraInvertida = new javax.swing.JButton();
        btA = new javax.swing.JButton();
        btD = new javax.swing.JButton();
        btF = new javax.swing.JButton();
        btG = new javax.swing.JButton();
        btH = new javax.swing.JButton();
        btJ = new javax.swing.JButton();
        btK = new javax.swing.JButton();
        btL = new javax.swing.JButton();
        btDoisPontos = new javax.swing.JButton();
        btAspas = new javax.swing.JButton();
        btS = new javax.swing.JButton();
        btEnter = new javax.swing.JButton();
        btZ = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btV = new javax.swing.JButton();
        btB = new javax.swing.JButton();
        btN = new javax.swing.JButton();
        btM = new javax.swing.JButton();
        btVirgula = new javax.swing.JButton();
        btPonto = new javax.swing.JButton();
        btInterrogacao = new javax.swing.JButton();
        btX = new javax.swing.JButton();
        btUp = new javax.swing.JButton();
        btRight = new javax.swing.JButton();
        btDown = new javax.swing.JButton();
        btLeft = new javax.swing.JButton();
        btSpace = new javax.swing.JButton();
        lblAcertos = new javax.swing.JLabel();
        acertos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        btOne.setText("1");

        btTil.setText("~");

        btTwo.setText("2");
        btTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTwoActionPerformed(evt);
            }
        });

        btThree.setText("3");

        btFour.setText("4");

        btFive.setText("5");

        btSix.setText("6");

        btSeven.setText("7");

        btEight.setText("8");

        btNine.setText("9");

        btZero.setText("0");

        btMinus.setText("-");

        btBackspace.setText("Backspace");

        btTab.setText("Tab");

        btCaps.setText("Caps");

        btShift.setText("Shift");

        btP.setText("P");

        btColcheteEsquerdo.setText("[");

        btW.setText("W");

        btColcheteDireito.setText("]");

        btQ.setText("Q");

        btE.setText("E");

        btR.setText("R");

        btT.setText("T");

        btY.setText("Y");

        btU.setText("U");

        btI.setText("I");

        btO.setText("O");

        btBarraInvertida.setText("\\");

            btA.setText("A");

            btD.setText("D");

            btF.setText("F");

            btG.setText("G");

            btH.setText("H");

            btJ.setText("J");

            btK.setText("K");

            btL.setText("L");

            btDoisPontos.setText(":");

            btAspas.setText("\"");

            btS.setText("S");

            btEnter.setText("Enter");

            btZ.setText("Z");

            btC.setText("C");

            btV.setText("V");

            btB.setText("B");

            btN.setText("N");

            btM.setText("M");

            btVirgula.setText(",");

            btPonto.setText(".");

            btInterrogacao.setText("?");

            btX.setText("X");

            btUp.setText("^");

            btRight.setText(">");

            btDown.setText("v");

            btLeft.setText("<");

            acertos.setText("jLabel1");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(btTil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btOne, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btThree, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btFour, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btFive, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btSix, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btEight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btNine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btZero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btCaps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btShift, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAcertos)
                                .addComponent(acertos))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)
                                    .addComponent(btLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btDown, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btRight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btG, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btH, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btJ, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btK, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btDoisPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btAspas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btQ, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btW, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btE, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btY, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btU, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btI, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btColcheteEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btColcheteDireito, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btBarraInvertida, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btZ, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btX, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btV, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btN, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(btInterrogacao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(51, 51, 51)
                                            .addComponent(btUp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 17, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(28, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btTil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btOne, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btThree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btFour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btFive, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSix, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btEight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btZero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btTab, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btQ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btW, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btY, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btU, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btColcheteEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btColcheteDireito, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBarraInvertida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btJ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDoisPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAspas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btInterrogacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btShift, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btZ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btX, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btUp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btRight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btDown, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblAcertos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(acertos)
                            .addGap(24, 24, 24))))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTwoActionPerformed

    private void checkText(){        
        String textArea = jTextArea1.getText();
        String textLabel = lblText.getText();
        acertos.setText(String.valueOf(p.getAcerto()));
        
        if(textArea.equals(textLabel)){
            JOptionPane.showMessageDialog(this, "Voce terminou o texto: Acerto" + p.getAcerto() + " Erro:" + p.getErro());
            this.setVisible(false);
            dispose();
        }
    }
    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_A){
            btA.setBackground(Color.red);
            p.checkValue(lblText.getText(), 'a');
        }
        if(evt.getKeyCode() == evt.VK_B){
            btB.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'b');

        }
        if(evt.getKeyCode() == evt.VK_C){
            btC.setBackground(Color.red);
            p.checkValue(lblText.getText(), 'c');
        }
        if(evt.getKeyCode() == evt.VK_D){
            btD.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'd');

        }
        if(evt.getKeyCode() == evt.VK_E){
            btE.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'e');

        }
        if(evt.getKeyCode() == evt.VK_F){
            btF.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'f');

        }
        if(evt.getKeyCode() == evt.VK_G){
            btG.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'g');

        }
        if(evt.getKeyCode() == evt.VK_H){
            btH.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'h');

        }
        if(evt.getKeyCode() == evt.VK_I){
            btI.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'i');

        }
        if(evt.getKeyCode() == evt.VK_J){
            btJ.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'j');

        }
        if(evt.getKeyCode() == evt.VK_K){
            btK.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'k');

        }
        if(evt.getKeyCode() == evt.VK_L){
            btL.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'l');

        }
        if(evt.getKeyCode() == evt.VK_M){
            btM.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'm');

        }
        if(evt.getKeyCode() == evt.VK_N){
            btN.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'n');

        }
        if(evt.getKeyCode() == evt.VK_O){
            btO.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'o');

        }
        if(evt.getKeyCode() == evt.VK_P){
            btP.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'p');

        }
        if(evt.getKeyCode() == evt.VK_Q){
            btQ.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'q');

        }
        if(evt.getKeyCode() == evt.VK_R){
            btR.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'r');

        }
        if(evt.getKeyCode() == evt.VK_S){
            btS.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 's');

        }
        if(evt.getKeyCode() == evt.VK_T){
            btT.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 't');

        }
        if(evt.getKeyCode() == evt.VK_U){
            btU.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'u');

        }
        if(evt.getKeyCode() == evt.VK_V){
            btV.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'v');

        }
        if(evt.getKeyCode() == evt.VK_W){
            btW.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'w');

        }
        if(evt.getKeyCode() == evt.VK_X){
            btX.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'x');

        }
        if(evt.getKeyCode() == evt.VK_Y){
            btY.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'y');

        }
        if(evt.getKeyCode() == evt.VK_Z){
            btZ.setBackground(Color.red);
                    p.checkValue(lblText.getText(), 'z');

        }
        
        if(evt.getKeyCode() == evt.VK_1){
            btOne.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_2){
            btTwo.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_3){
            btThree.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_4){
            btFour.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_5){
            btFive.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_6){
            btSix.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_7){
            btSeven.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_8){
            btEight.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_9){
            btNine.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_0){
            btZero.setBackground(Color.red);
        }
        
        
        if(evt.getKeyCode() == evt.VK_CIRCUMFLEX){
            btTil.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_MINUS){
            btMinus.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_BACK_SPACE){
            btBackspace.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_TAB){
            btTab.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_CAPS_LOCK){
            btCaps.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_COMMA){
            btVirgula.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_PERIOD){
            btPonto.setBackground(Color.red);
        }
        
        if(evt.getKeyCode() == evt.VK_SHIFT){
            btShift.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_OPEN_BRACKET){
            btColcheteEsquerdo.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_CLOSE_BRACKET){
            btColcheteDireito.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_BACK_SLASH){
            btBarraInvertida.setBackground(Color.red);
        }
        
        if(evt.getKeyCode() == evt.VK_COLON){
            btDoisPontos.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_QUOTE){
            btAspas.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_ENTER){
            btEnter.setBackground(Color.red);
        }
        
        if(evt.getKeyCode() == evt.VK_UP){
            btUp.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_DOWN){
            btDown.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_LEFT){
            btLeft.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_RIGHT){
            btRight.setBackground(Color.red);
        }
        if(evt.getKeyCode() == evt.VK_SPACE){
            btSpace.setBackground(Color.red);
                                p.checkValue(lblText.getText(), ' ');

        }
        
        checkText();
                
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        // TODO add your handling code here:
        Color c = new Color(249,249,248);
        
        if(evt.getKeyCode() == evt.VK_A){
            btA.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_B){
            btB.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_C){
            btC.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_D){
            btD.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_E){
            btE.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_F){
            btF.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_G){
            btG.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_H){
            btH.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_I){
            btI.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_J){
            btJ.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_K){
            btK.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_L){
            btL.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_M){
            btM.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_N){
            btN.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_O){
            btO.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_P){
            btP.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_Q){
            btQ.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_R){
            btR.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_S){
            btS.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_T){
            btT.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_U){
            btU.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_V){
            btV.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_W){
            btW.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_X){
            btX.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_Y){
            btY.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_Z){
            btZ.setBackground(c);
        }
        
        if(evt.getKeyCode() == evt.VK_1){
            btOne.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_2){
            btTwo.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_3){
            btThree.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_4){
            btFour.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_5){
            btFive.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_6){
            btSix.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_7){
            btSeven.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_8){
            btEight.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_9){
            btNine.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_0){
            btZero.setBackground(c);
        }
        
        
        if(evt.getKeyCode() == evt.VK_CIRCUMFLEX){
            btTil.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_MINUS){
            btMinus.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_BACK_SPACE){
            btBackspace.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_TAB){
            btTab.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_CAPS_LOCK){
            btCaps.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_COMMA){
            btVirgula.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_PERIOD){
            btPonto.setBackground(c);
        }
        
        if(evt.getKeyCode() == evt.VK_SHIFT){
            btShift.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_OPEN_BRACKET){
            btColcheteEsquerdo.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_CLOSE_BRACKET){
            btColcheteDireito.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_BACK_SLASH){
            btBarraInvertida.setBackground(c);
        }
        
        if(evt.getKeyCode() == evt.VK_COLON){
            btDoisPontos.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_QUOTE){
            btAspas.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_ENTER){
            btEnter.setBackground(c);
        }
        
        if(evt.getKeyCode() == evt.VK_UP){
            btUp.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_DOWN){
            btDown.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_LEFT){
            btLeft.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_RIGHT){
            btRight.setBackground(c);
        }
        if(evt.getKeyCode() == evt.VK_SPACE){
            btSpace.setBackground(c);
        }
        
        checkText();

    }//GEN-LAST:event_jTextArea1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acertos;
    private javax.swing.JButton btA;
    private javax.swing.JButton btAspas;
    private javax.swing.JButton btB;
    private javax.swing.JButton btBackspace;
    private javax.swing.JButton btBarraInvertida;
    private javax.swing.JButton btC;
    private javax.swing.JButton btCaps;
    private javax.swing.JButton btColcheteDireito;
    private javax.swing.JButton btColcheteEsquerdo;
    private javax.swing.JButton btD;
    private javax.swing.JButton btDoisPontos;
    private javax.swing.JButton btDown;
    private javax.swing.JButton btE;
    private javax.swing.JButton btEight;
    private javax.swing.JButton btEnter;
    private javax.swing.JButton btF;
    private javax.swing.JButton btFive;
    private javax.swing.JButton btFour;
    private javax.swing.JButton btG;
    private javax.swing.JButton btH;
    private javax.swing.JButton btI;
    private javax.swing.JButton btInterrogacao;
    private javax.swing.JButton btJ;
    private javax.swing.JButton btK;
    private javax.swing.JButton btL;
    private javax.swing.JButton btLeft;
    private javax.swing.JButton btM;
    private javax.swing.JButton btMinus;
    private javax.swing.JButton btN;
    private javax.swing.JButton btNine;
    private javax.swing.JButton btO;
    private javax.swing.JButton btOne;
    private javax.swing.JButton btP;
    private javax.swing.JButton btPonto;
    private javax.swing.JButton btQ;
    private javax.swing.JButton btR;
    private javax.swing.JButton btRight;
    private javax.swing.JButton btS;
    private javax.swing.JButton btSeven;
    private javax.swing.JButton btShift;
    private javax.swing.JButton btSix;
    private javax.swing.JButton btSpace;
    private javax.swing.JButton btT;
    private javax.swing.JButton btTab;
    private javax.swing.JButton btThree;
    private javax.swing.JButton btTil;
    private javax.swing.JButton btTwo;
    private javax.swing.JButton btU;
    private javax.swing.JButton btUp;
    private javax.swing.JButton btV;
    private javax.swing.JButton btVirgula;
    private javax.swing.JButton btW;
    private javax.swing.JButton btX;
    private javax.swing.JButton btY;
    private javax.swing.JButton btZ;
    private javax.swing.JButton btZero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
